spring:
  application:
    name: coffees
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:coffees-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active:
      - default
logging:
  level:
    org:
      springframework:
        security: TRACE
jwt:
  secret: somereaaaaaaaaaaaaaaaaaalllllllllllyyystrongsecret
